'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3082
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Memory_1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property demoman_go02() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("demoman_go02", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property engineer_niceshot02() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("engineer_niceshot02", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property flame_thrower_fire_hit() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("flame_thrower_fire_hit", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property flame_thrower_pilot() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("flame_thrower_pilot", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property heavy_domination17() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("heavy_domination17", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Heavynew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Heavynew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Link4Swords() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Link4Swords", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LinkBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LinkBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LinkMinishCap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LinkMinishCap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LinkOcOfTime() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LinkOcOfTime", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LinkOriginal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LinkOriginal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LinkPHour() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LinkPHour", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LinkTP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LinkTP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LinkWindwaker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LinkWindwaker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LinkWolf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LinkWolf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PikminBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PikminBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PikminBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PikminBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PikminLouie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PikminLouie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PikminOlimar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PikminOlimar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PikminPurple() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PikminPurple", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PikminRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PikminRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PikminRLL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PikminRLL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PikminWall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PikminWall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PikminWhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PikminWhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PikminYellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PikminYellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RedCardBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedCardBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RedDemo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedDemo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RedEngee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedEngee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RedHeavy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedHeavy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RedPyro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedPyro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RedScout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedScout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RedSniper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedSniper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RedSoldier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedSoldier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RedSpy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedSpy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property scout_award02() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("scout_award02", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property scout_award08() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("scout_award08", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property sniper_award04() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("sniper_award04", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property soldier_battlecry03() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("soldier_battlecry03", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property spy_battlecry01() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("spy_battlecry01", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property tf2Back1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tf2Back1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
