'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Platfomer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property blood1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blood1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blood10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blood10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blood11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blood11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blood12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blood12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blood13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blood13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blood14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blood14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blood15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blood15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blood2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blood2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blood3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blood3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blood4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blood4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blood5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blood5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blood6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blood6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blood7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blood7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blood8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blood8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blood9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blood9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bomb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bomb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BulletHoriz2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BulletHoriz2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BulletVert2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BulletVert2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property door1_40by50_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("door1(40by50)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property doorOpen1_40by50_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("doorOpen1(40by50)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ExplosionLvl3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExplosionLvl3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ExplosionLvl5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExplosionLvl5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ExplosionLvl5Lose() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExplosionLvl5Lose", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FallLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FallLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FallRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FallRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property glasses() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("glasses", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gravity() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gravity", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gravity1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gravity1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HitWallLeft2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HitWallLeft2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HitWallRight2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HitWallRight2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property JumpLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JumpLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property JumpRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JumpRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Key1_17by36_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Key1(17by36)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property portalDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portalDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property portalUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portalUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RunLeftFixed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RunLeftFixed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RunRightFixed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RunRightFixed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sentry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sentry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Spike2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Spike2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splodeLvl3_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splodeLvl3-9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Still01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Still01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property StillGlasses() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StillGlasses", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TurretHoriz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurretHoriz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TurretHoriz1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurretHoriz1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TurretVert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurretVert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
