//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chips_Challenge.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chips_Challenge.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap backgroundNew {
            get {
                object obj = ResourceManager.GetObject("backgroundNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ball {
            get {
                object obj = ResourceManager.GetObject("ball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blob {
            get {
                object obj = ResourceManager.GetObject("Blob", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueWall {
            get {
                object obj = ResourceManager.GetObject("BlueWall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bomb {
            get {
                object obj = ResourceManager.GetObject("Bomb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChipTile {
            get {
                object obj = ResourceManager.GetObject("ChipTile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChipWaterLeft {
            get {
                object obj = ResourceManager.GetObject("ChipWaterLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChipWaterNormal {
            get {
                object obj = ResourceManager.GetObject("ChipWaterNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChipWaterRight {
            get {
                object obj = ResourceManager.GetObject("ChipWaterRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChipWaterUp {
            get {
                object obj = ResourceManager.GetObject("ChipWaterUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dirt {
            get {
                object obj = ResourceManager.GetObject("Dirt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DirtInWater {
            get {
                object obj = ResourceManager.GetObject("DirtInWater", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DoorBlue {
            get {
                object obj = ResourceManager.GetObject("DoorBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DoorGreen {
            get {
                object obj = ResourceManager.GetObject("DoorGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DoorRed {
            get {
                object obj = ResourceManager.GetObject("DoorRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DoorTile {
            get {
                object obj = ResourceManager.GetObject("DoorTile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DoorYellow {
            get {
                object obj = ResourceManager.GetObject("DoorYellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fireball {
            get {
                object obj = ResourceManager.GetObject("fireball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FireBoot {
            get {
                object obj = ResourceManager.GetObject("FireBoot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FireTile {
            get {
                object obj = ResourceManager.GetObject("FireTile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flipper {
            get {
                object obj = ResourceManager.GetObject("Flipper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FloorTile {
            get {
                object obj = ResourceManager.GetObject("FloorTile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ForceFloorRandom {
            get {
                object obj = ResourceManager.GetObject("ForceFloorRandom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gravel {
            get {
                object obj = ResourceManager.GetObject("Gravel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GuyDeadFire {
            get {
                object obj = ResourceManager.GetObject("GuyDeadFire", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GuyDeadWater {
            get {
                object obj = ResourceManager.GetObject("GuyDeadWater", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GuyLeft {
            get {
                object obj = ResourceManager.GetObject("GuyLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GuyNormal {
            get {
                object obj = ResourceManager.GetObject("GuyNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GuyRight {
            get {
                object obj = ResourceManager.GetObject("GuyRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GuyUp {
            get {
                object obj = ResourceManager.GetObject("GuyUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HUD {
            get {
                object obj = ResourceManager.GetObject("HUD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hud_Help {
            get {
                object obj = ResourceManager.GetObject("Hud_Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IceSkate {
            get {
                object obj = ResourceManager.GetObject("IceSkate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IceTile {
            get {
                object obj = ResourceManager.GetObject("IceTile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KeyBlue {
            get {
                object obj = ResourceManager.GetObject("KeyBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KeyGreen {
            get {
                object obj = ResourceManager.GetObject("KeyGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KeyRed {
            get {
                object obj = ResourceManager.GetObject("KeyRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KeyYellow {
            get {
                object obj = ResourceManager.GetObject("KeyYellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 080/999
        ///WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-;
        ///WW-WW-WW-WW-WW-WW-WW-WW-WN-WW-;
        ///WW-WW-WW-KR-FL-WW-WW-WW-DO-WW-WW-WW-;
        ///WW-WW-WW-FL-FL-WW-FL-FL-FL-FL-FL-WW-WW-WW-WW-WW-;
        ///WW-WW-WW-FL-FL-DG-FL-FL-FL-FL-FL-WA-WA-WA-CH-WW-;
        ///WW-WW-WW-FL-FL-WW-KG-FL-FL-FL-FL-WW-WW-WW-WW-WW-;
        ///WW-WW-WW-CH-FL-WW-FL-FL-HP-FL-FL-WW-WW-WW-WW-WW-;
        ///WW-WW-WW-WW-WW-WW-FL-FL-SP-FL-FL-WW-FL-FI-FL-WW-;
        ///WW-WW-WW-WW-FL-DR-FL-FL-FL-FL-FL-DY-FL-FI-CH-WW-WW-WW-;
        ///WW-WW-KY-WW-FL-WW-FL-FL-FL-FL-FL-WW-FL-FI-FL-FL-IS-WW-;
        ///WW-WW-FL-WW-FL-WW-WW-WW-IC-WW [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level_1 {
            get {
                return ResourceManager.GetString("Level_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 222/999
        ///FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-;
        ///FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-WW-NW-IC-IC-IC-IC-IC-IC-FL-FL-FL-WW-WW-WW-WW-WW-WW-WW-WW-WW-;
        ///FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-WW-IC-WW-WW-WW-WW-WW-WW-WW-WW-FL-WW-WW-WW-WW-WW-WW-WW-WW-WW-;
        ///WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-IC-WW-WW-WW-WW-WW-WW-WW-WW-FL-IC-IC-IC-IC-IC-IC-IC-FI-WW-;
        ///WW-FI-IC-IC-IC-IC-IC-BO-IC-IC-IC-SE-WW-WW-WW-FL-FL-FL-FL-FL-FL-WW-WW-CH-WW-WW-FL-WW-WW-WW-;
        ///WW-WW-WW-WW-FL-WW-WW-FL-WW-WW-WW-WW-WW [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level_10 {
            get {
                return ResourceManager.GetString("Level_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250/999
        ///WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-;
        ///WW-GR-GR-GR-GR-GR-GR-GR-GR-GR-GR-GR-GR-GR-GR-GR-GR-GR-GR-GR-GR-GR-GR-GR-GR-GR-GR-GR-GR-GR-WW-;
        ///WW-GR-CH-CH-CH-GR-CH-FL-FL-GR-FL-FL-FL-GR-FL-FL-BL-GR-FL-FL-FL-GR-FL-CH-FL-GR-FL-FL-BL-GR-WW-;
        ///WW-GR-CH-SP-CH-GR-FL-BL-FL-CH-FL-FL-FL-CH-FL-CH-FL-CH-FL-FL-BL-CH-FL-FL-FL-CH-FL-FL-FL-GR-WW-;
        ///WW-GR-CH-CH-CH-GR-FL-FL-FL-GR-FL-BL-CH-GR-FL-FL-FL-GR-FL-FL-CH-GR-FL-FL-FL-GR-FL-CH-FL-GR-WW-;
        ///WW-GR-GR-GR-GR-GR-GR-GR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level_11 {
            get {
                return ResourceManager.GetString("Level_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200/008
        ///WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-;
        ///WW-WW-WW-WW-WW-WW-FL-FL-FL-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-;
        ///WW-WW-WW-WW-WW-WW-FE-WW-FL-WW-WW-FL-FL-FL-FL-FL-FL-FL-FL-KR-WW-WW-WW-WW-WW-WW-;
        ///WW-WW-WW-FL-FL-FL-FL-WW-FL-FL-FL-FL-WW-WW-WW-WW-WW-FL-WW-WW-WW-WW-WW-WW-WW-WW-;
        ///WW-WW-WW-FL-WW-WW-FL-FL-FL-WW-WW-FL-WW-WW-WW-WW-WW-FL-WW-WW-WW-WW-WW-WW-WW-WW-;
        ///WW-FL-FL-FL-FL-WW-WW-WW-WW-WW-WW-FL-FI-FI-FI-FI-WW-FL-WW-WW-WW-WW-WW-CH-WW-WW-;
        ///WW-FL-FL-DT-FL-WW [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level_12 {
            get {
                return ResourceManager.GetString("Level_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Level_13 {
            get {
                return ResourceManager.GetString("Level_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100/999
        ///FL-FL-FL-FL-WW-WW-WW-WW-WW-WW-WW-WW-WW-;
        ///FL-WW-WW-WW-WW-SB-WW-WW-TB-WW-WW-FL-WW-;
        ///FL-WW-WN-DO-FL-FL-WW-WW-FL-WW-WW-FL-WW-;
        ///WW-WW-WW-WW-WW-FL-TW-FL-FL-FL-WW-BV-WW-;
        ///WW-FL-FL-FL-WW-WW-WW-FL-HP-FL-FL-FL-WW-;
        ///WW-CH-FI-FL-FL-FL-FL-FL-SP-FL-WW-FL-WW-;
        ///WW-FL-FL-FL-WW-FL-WW-FL-FL-FL-WW-FL-WW-WW-;
        ///WW-WW-WW-WW-WW-FL-WW-WW-FL-WW-WW-FL-CH-WW-;
        ///FL-FL-FL-FL-WW-TF-WW-WW-TF-WW-WW-WW-WW-WW-;
        ///FL-FL-FL-FL-WW-FL-WW-WW-PD-WW-;
        ///FL-WW-WW-WW-WW-PU-WW-WW-PD-WW-;
        ///FL-WW-CH-PR-PR-PU-PL-PL-PL-WW-;
        ///FL-WW-WW-WW-WW-WW [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level_2 {
            get {
                return ResourceManager.GetString("Level_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 070/999
        ///WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-;
        ///WW-FL-FL-FL-FL-SP-FL-FL-FL-FL-FL-FL-FL-WW-;
        ///WW-FL-FL-FL-FL-HP-FL-FL-FL-WW-WW-WW-FL-WW-;
        ///WW-WW-TW-TW-WW-WW-WW-TW-TW-WW-WW-WW-FL-WW-;
        ///WW-CH-FL-FL-FL-TE-FL-TB-FL-FL-TW-FL-FL-WW-;
        ///WW-WW-WW-WW-WW-WW-FL-WW-WW-WW-WW-WW-WW-WW-;
        ///FL-FL-FL-WW-WW-WW-FL-WW-WW-;
        ///FL-FL-FL-WW-FL-FL-FL-FL-WW-;
        ///FL-FL-FL-WW-FL-DT-FL-FL-WW-;
        ///FL-FL-FL-WW-FL-FL-FL-FL-WW-;
        ///FL-FL-FL-WW-WA-WA-WA-WA-WW-;
        ///FL-FL-FL-WW-FP-FL-FL-FL-WW-;
        ///FL-FL-FL-WW-FL-FL-WW-WW-WW-;
        ///WW-WW-WW-WW-WW-FL-WW-WW [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level_3 {
            get {
                return ResourceManager.GetString("Level_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200/999
        ///FL-FL-FL-FL-WW-WW-WW-WW-;
        ///WW-WW-WW-WW-WW-FL-WW-WW-WW-WW-WW-WW-WW-WW-;
        ///WW-SP-FL-FL-WW-FL-WW-FL-WW-WW-FL-FL-FL-WW-;
        ///WW-WW-WW-FL-FL-FL-FL-FL-WW-WW-FL-WW-FL-WW-;
        ///WW-FL-FL-WW-WW-FL-WW-FL-WW-WW-FL-WW-FL-WW-;
        ///WW-FL-FL-FL-WW-TW-WW-FL-WW-WW-FL-WW-FL-WW-;
        ///WW-FL-FL-FL-WW-BV-WW-TB-WW-WW-FL-WW-FL-WW-WW-WW-WW-WW-WW-;
        ///WW-FL-FL-FL-WW-FL-WW-CH-WW-WW-SB-WW-FL-FL-FL-FL-FL-BH-WW-;
        ///WW-FL-FL-FL-WW-TB-WW-WW-WW-WW-TF-WW-WW-WW-FL-WW-WW-WW-WW-;
        ///WW-FL-WW-WW-FL-FL-WW-WW-WW-CH-FL-CH-WW-WW-FL-WW-WW-;
        ///WW-FL-WW-FL-FL-FL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level_4 {
            get {
                return ResourceManager.GetString("Level_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200/999
        ///WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-;
        ///WW-FI-FI-FI-FI-FI-FI-FI-FI-FI-FI-FI-FI-FI-FI-FI-FI-FI-FI-FI-FI-FI-FI-FI-FI-FI-FI-FI-FI-FI-WW-;
        ///WW-FI-SP-IC-IC-IC-IC-IC-FL-IC-IC-IC-FL-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-FI-WW-;
        ///WW-FI-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-FI-WW-;
        ///WW-FI-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-IC-FI-WW-;
        ///WW-FI-IC-IC-IC-IC-IC-IC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level_5 {
            get {
                return ResourceManager.GetString("Level_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 700/599
        ///WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-;
        ///WW-SP-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-WW-;
        ///WW-FL-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-FL-WW-;
        ///WW-FL-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-FL-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-FL-WW-;
        ///WW-FL-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-WK-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH-CH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level_6 {
            get {
                return ResourceManager.GetString("Level_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 050/000
        ///WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-;
        ///WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-WW-RW-RW-RW-RW-WW-;
        ///WW-RW-RW-RW-RW-RW-RW-RW-RW-RW-RW-RW-RW-RW-RW-RW-WW-WW-WW-RW-WW-;
        ///WW-RW-WW-WW-WW-WW-WW-WW-WW-WW-RW-WW-WW-WW-WW-RW-WW-WW-WW-RW-WW-;
        ///WW-RW-WW-WW-WW-WW-RW-WW-WW-WW-RW-WW-WW-WW-WW-RW-RW-WW-RW-RW-WW-;
        ///WW-RW-WW-WW-WW-WW-RW-WW-WW-WW-RW-WW-WW-WW-WW-RW-WW-WW-WW-RW-WW-;
        ///WW-RW-WW-RW-RW-RW-RW-RW-RW-WW-RW-WW-WW-WW-WW-RW-WW-WW-WW-RW-WW-;
        ///WW-RW-WW-RW-WW-RW-WW-WW-RW-WW-RW-WW-WW-WW [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level_7 {
            get {
                return ResourceManager.GetString("Level_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100/999
        ///WW-WW-WW-WW-WW-WW-;
        ///WW-FL-FL-FL-FL-WW-WW-WW-WW-WW-;
        ///WW-WW-DT-WW-FL-FL-FL-DT-FL-WW-;
        ///FL-WW-FL-WW-FL-WW-WW-WW-FL-WW-;
        ///WW-WW-FL-WW-FL-FL-FL-FL-FL-WW-WW-WW-WW-WW-WW-WW-;
        ///WW-FL-DT-FL-FL-DT-WW-FL-FL-WA-WA-WA-WA-DO-WN-WW-;
        ///WW-FL-WW-WW-SP-FL-FL-FL-FL-WW-WW-WW-WW-WW-WW-WW-;
        ///WW-FL-FL-FL-FL-FL-FL-FL-FL-WW-;
        ///WW-FL-FL-FL-FL-FL-FL-FL-FL-WW-;
        ///WW-WW-WW-WW-FL-WW-FL-WW-WW-WW-;
        ///FL-FL-FL-WW-PD-WW-FL-WW-;
        ///FL-FL-FL-WW-FL-WW-RW-WW-;
        ///WW-WW-WW-WW-FL-WW-FL-WW-;
        ///WW-FL-FL-FL-FL-FL-FL-WW-;
        ///WW-FL-DT-FL-DT-FL-FL-WW [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level_8 {
            get {
                return ResourceManager.GetString("Level_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200/999
        ///HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-;
        ///HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-;
        ///HW-HW-HW-FL-CH-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-HW-;
        ///HW-HW-HW-FL-HW-HW-HW-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-FL-HW-FL-FL-FL-FL-HW-;
        ///HW-HW-HW-FL-HW-HW-HW-FL-HW-HW-HW-HW-HW-FL-HW-HW-FL-HW-HW-HW-HW-HW-FL-HW-FL-HW-FL-HW-HW-FL-HW-;
        ///HW-HW-HW-FL-HW-HW-HW-FL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level_9 {
            get {
                return ResourceManager.GetString("Level_9", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap LevelIntro {
            get {
                object obj = ResourceManager.GetObject("LevelIntro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MonsterLeft {
            get {
                object obj = ResourceManager.GetObject("MonsterLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MonsterNormal {
            get {
                object obj = ResourceManager.GetObject("MonsterNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MonsterRight {
            get {
                object obj = ResourceManager.GetObject("MonsterRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MonsterUp {
            get {
                object obj = ResourceManager.GetObject("MonsterUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NEice {
            get {
                object obj = ResourceManager.GetObject("NEice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NWice {
            get {
                object obj = ResourceManager.GetObject("NWice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PushDown {
            get {
                object obj = ResourceManager.GetObject("PushDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PushLeft {
            get {
                object obj = ResourceManager.GetObject("PushLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PushRight {
            get {
                object obj = ResourceManager.GetObject("PushRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PushUp {
            get {
                object obj = ResourceManager.GetObject("PushUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RecessedWall {
            get {
                object obj = ResourceManager.GetObject("RecessedWall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SEice {
            get {
                object obj = ResourceManager.GetObject("SEice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SuctionBoots {
            get {
                object obj = ResourceManager.GetObject("SuctionBoots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWice {
            get {
                object obj = ResourceManager.GetObject("SWice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Theif {
            get {
                object obj = ResourceManager.GetObject("Theif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tmr0 {
            get {
                object obj = ResourceManager.GetObject("Tmr0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tmr1 {
            get {
                object obj = ResourceManager.GetObject("Tmr1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tmr2 {
            get {
                object obj = ResourceManager.GetObject("Tmr2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tmr3 {
            get {
                object obj = ResourceManager.GetObject("Tmr3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tmr4 {
            get {
                object obj = ResourceManager.GetObject("Tmr4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tmr5 {
            get {
                object obj = ResourceManager.GetObject("Tmr5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tmr6 {
            get {
                object obj = ResourceManager.GetObject("Tmr6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tmr7 {
            get {
                object obj = ResourceManager.GetObject("Tmr7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tmr8 {
            get {
                object obj = ResourceManager.GetObject("Tmr8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tmr9 {
            get {
                object obj = ResourceManager.GetObject("Tmr9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TmrYellow {
            get {
                object obj = ResourceManager.GetObject("TmrYellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToggleButton {
            get {
                object obj = ResourceManager.GetObject("ToggleButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToggleFloor {
            get {
                object obj = ResourceManager.GetObject("ToggleFloor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToggleWall {
            get {
                object obj = ResourceManager.GetObject("ToggleWall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WalkerLeft {
            get {
                object obj = ResourceManager.GetObject("WalkerLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WalkerRight {
            get {
                object obj = ResourceManager.GetObject("WalkerRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WallTile {
            get {
                object obj = ResourceManager.GetObject("WallTile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WaterTile {
            get {
                object obj = ResourceManager.GetObject("WaterTile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WinTile {
            get {
                object obj = ResourceManager.GetObject("WinTile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
